source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'TableViewModel_Example', :exclusive => true do
  pod "TableViewModel", :path => "../"
end

target 'TableViewModel_Tests', :exclusive => true do
  pod "TableViewModel", :path => "../"

  pod 'Quick'
  pod 'Nimble'
end
