source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

platform :ios, '8.3'
inhibit_all_warnings!

target 'TableViewModel_Example' do
  pod "TableViewModel", :path => "../"
end

target 'TableViewModel_Tests' do
  pod "TableViewModel", :path => "../"

  pod 'Quick'
  pod 'Nimble'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '3.0'
    end
  end
end
